<?php
/**
 * Database Configuration Template
 * 
 * This file is auto-generated by deployment scripts.
 * You can manually edit it to change database settings.
 */

// Database type: 'sqlite' or 'mysql'
define('DB_TYPE', 'sqlite');

// SQLite Configuration
define('DB_PATH', __DIR__ . '/../database/app.db');

// MySQL Configuration (uncomment and configure if using MySQL)
// define('DB_HOST', 'localhost');
// define('DB_NAME', 'spa_db');
// define('DB_USER', 'spa_user');
// define('DB_PASS', 'spa_password123');
// define('DB_CHARSET', 'utf8mb4');
// define('DB_PORT', 3306);

/**
 * Get PDO Database Connection
 * 
 * @return PDO
 */
function getDbConnection() {
    try {
        if (DB_TYPE === 'mysql') {
            $dsn = sprintf(
                'mysql:host=%s;dbname=%s;charset=%s',
                DB_HOST,
                DB_NAME,
                DB_CHARSET ?? 'utf8mb4'
            );
            
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];
            
            return new PDO($dsn, DB_USER, DB_PASS, $options);
        } else {
            // SQLite
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ];
            
            return new PDO('sqlite:' . DB_PATH, null, null, $options);
        }
    } catch (PDOException $e) {
        die('Database connection failed: ' . $e->getMessage());
    }
}
